# Generated by Django 5.1.7 on 2025-05-26 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0003_alter_job_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='expertise_level',
            field=models.CharField(choices=[('ENTRY-LEVEL', 'Entry-Level'), ('JUNIOR', 'Junior'), ('INTERMEDIATE', 'Intermediate'), ('EXPERT', 'Expert')], default=None, max_length=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='pricing_type',
            field=models.CharField(choices=[('FIXED', 'Fixed'), ('CONTRACTUAL', 'Contractual'), ('HOURLY', 'Hourly'), ('PROJECT-BASED', 'Project-based')], default=None, max_length=13),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='job',
            name='description',
            field=models.TextField(max_length=500),
        ),
    ]
