# Generated by Django 5.1.7 on 2025-05-28 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0004_job_expertise_level_job_pricing_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='expertise_level',
            field=models.CharField(blank=True, choices=[('ENTRY-LEVEL', 'Entry-Level'), ('JUNIOR', 'Junior'), ('INTERMEDIATE', 'Intermediate'), ('EXPERT', 'Expert')], max_length=12, null=True),
        ),
    ]
