# Generated by Django 5.1.7 on 2025-05-28 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0005_alter_job_expertise_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='expertise_level',
            field=models.CharField(choices=[('ENTRY-LEVEL', 'Entry-Level'), ('JUNIOR', 'Junior'), ('INTERMEDIATE', 'Intermediate'), ('EXPERT', 'Expert')], default=1, max_length=12),
            preserve_default=False,
        ),
    ]
